# Generated by Django 2.2.12 on 2020-05-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20200524_1702'),
        ('blogging', '0003_auto_20200526_2006'),
    ]

    operations = [
    ]
